### PR TITLE
fix color mode and uploader

### PR DESCRIPTION
**Pull request by Turtlepaw**

### CODE REVIEW

**Comment by Antouto** [comment]
I added the ColorModeScript to _app.tsx and it worked, so the _document.tsx file seems unnecessary tbh

**Comment by Turtlepaw** [comment]
That's what it says in the chakra UI docs

**Comment by Turtlepaw** [comment]
https://chakra-ui.com/docs/styled-system/color-mode#for-nextjs

**Comment by Antouto** [comment]
It seems to work so I'm not worrying about the docs

**Pull request merged**
